kind: Secret
apiVersion: v1
metadata:
  name: ldap-bind-secret-ci
  namespace: ci
  annotations:
    argocd.argoproj.io/sync-wave: '207'
data:
  ldapPassword: UGFzc3cwcmQ=
  ldapUsername: Y249YWRtaW4sZGM9Y3A=
type: Opaque