kind: Secret
apiVersion: v1
metadata:
  name: openldap-openldap-stack-ha
  namespace: openldap
  annotations:
    argocd.argoproj.io/sync-wave: "205"
data:
  LDAP_ADMIN_PASSWORD: UGFzc3cwcmQ=
  LDAP_CONFIG_PASSWORD: UGFzc3cwcmQ=
type: Opaque
