kind: Service
apiVersion: v1
metadata:
  name: openldap-phpldapadmin
  namespace: openldap
  annotations:
    argocd.argoproj.io/sync-wave: "240"
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: phpldapadmin
    release: openldap
