kind: Deployment
apiVersion: apps/v1
metadata:
  name: openldap-phpldapadmin
  namespace: openldap
  annotations:
    argocd.argoproj.io/sync-wave: "230"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpldapadmin
      release: openldap
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: phpldapadmin
        release: openldap
    spec:
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: phpldapadmin
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: openldap-phpldapadmin
          image: 'osixia/phpldapadmin:0.9.0'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600