kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: db2u-setup-rolebinding
subjects:
  - kind: ServiceAccount
    name: db2u-setup
    namespace: db2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: db2u-setup-role
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit
subjects:
  - kind: ServiceAccount
    name: db2u-setup
    namespace: db2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
