apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "240"
  name: ibm-cp4ba-operator-subscription-ci
  namespace: cp4ba
spec:
  # channel: v22.1
  channel: v22.1
  name: ibm-cp4a-operator-ci
  installPlanApproval: Automatic
  source: ibm-cp4a-operator-catalog-ci
  sourceNamespace: openshift-marketplace