kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odm-postdeploy-role
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - route.openshift.io
    resources:
      - route
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - secret
