apiVersion: db2u.databases.ibm.com/v1
kind: Db2uCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "230"
  name: db2ucluster-cp4ba
  namespace: db2
spec:
  license:
    accept: true
  account:
    privileged: true
    imagePullSecrets:
      - ibm-entitlement-key   
  version: "11.5.7.0-cn5"
  size: 1
  podConfig:
    db2u:
      resource:
        db2u:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 8
            memory: 16Gi
  environment:
    dbType: db2oltp
    database:
      name: bludb
    instance:
      password: Passw0rd
      registry:
        DB2_4K_DEVICE_SUPPORT: "ON"
  addOns:    
    rest:     
      enabled: false
    graph:     
      enabled: false
  storage:
    - name: meta
      type: "create"
      spec:
        storageClassName: ocs-storagecluster-cephfs
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
    - name: data
      type: "create"
      spec:
        storageClassName: ocs-storagecluster-cephfs
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi