apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: decision-center
spec:
  href: https://cpd-cp4ba.apps.ocp-6630023d5n-obrm.cloud.techzone.ibm.com/odm/decisioncenter
  location: ApplicationMenu
  applicationMenu:
    section: Operational Decision Manager
  text: Decision Center
