resources:
# - sa.yaml
# - role.yaml
# - rolebinding.yaml
# - anyuid-rolebinding.yaml
- create-cp4d-data-governance-artifacts-job.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "415"

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: cp4d-data-governance-artifacts
  behavior: create
  files:
    - data-governance-artifacts.zip
- name: cp4d-data-governance-artifacts-scripts
  behavior: create
  files:
    - create-cp4d-data-governance-artifacts.sh
