kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: db2u-setup-role
rules:
  - verbs:
      - get
      - list
      - watch
      - create
    apiGroups:
      - ''
    resources:
      - pods
      - pods/status
      - pods/exec
