global: {}
service-account:
  name: db2
  create: false
  sccs: ["privileged"]

ibm-sfg-db2:
  name: db2
  replicaCount: 1
  serviceName: db2
  serviceAccount: db2
  image:
    repository: ibmcom/db2:11.5.7.0
    pullPolicy: IfNotPresent
  storageClassName: ibmc-block-gold
  createdb: |
    CREATE DATABASE PEMDB AUTOMATIC STORAGE YES USING CODESET UTF-8 TERRITORY DEFAULT COLLATE USING IDENTITY PAGESIZE 4096;
    CONNECT TO PEMDB;
    UPDATE DATABASE CONFIG FOR PEMDB USING LOGFILSIZ 65536;
    UPDATE DATABASE CONFIG FOR PEMDB USING LOGPRIMARY 40;
    UPDATE DATABASE CONFIG FOR PEMDB USING NUM_LOG_SPAN 32;
    UPDATE DATABASE CONFIG FOR PEMDB USING AUTO_MAINT ON;
    UPDATE DATABASE CONFIG FOR PEMDB USING AUTO_TBL_MAINT ON;
    UPDATE DATABASE CONFIG FOR PEMDB USING AUTO_RUNSTATS ON;
    UPDATE DATABASE CONFIG FOR PEMDB USING AUTO_REORG ON;
    UPDATE DATABASE CONFIG FOR PEMDB USING AUTO_DB_BACKUP ON;
    UPDATE DATABASE CONFIG FOR PEMDB USING NCHAR_MAPPING GRAPHIC_CU16;
    CREATE USER TEMPORARY TABLESPACE B2BUSERTEMP PAGESIZE 32K BUFFERPOOL IBMDEFAULTBP;
    CREATE BUFFERPOOL PEMDB_04KBP IMMEDIATE SIZE 1000 PAGESIZE 4K;
    CREATE REGULAR TABLESPACE TS_REG04_PEMDB PAGESIZE 4K BUFFERPOOL PEMDB_04KBP;
    CREATE BUFFERPOOL PEMDB_08KBP IMMEDIATE SIZE 1000 PAGESIZE 8K;
    CREATE REGULAR TABLESPACE TS_REG08_PEMDB PAGESIZE 8K BUFFERPOOL PEMDB_08KBP;
    CREATE BUFFERPOOL PEMDB_16KBP IMMEDIATE SIZE 1000 PAGESIZE 16K;
    CREATE REGULAR TABLESPACE TS_REG16_PEMDB PAGESIZE 16K BUFFERPOOL PEMDB_16KBP;
    CREATE BUFFERPOOL PEMDB_32KBP IMMEDIATE SIZE 1000 PAGESIZE 32K;
    CREATE REGULAR TABLESPACE TS_REG32_PEMDB PAGESIZE 32K BUFFERPOOL PEMDB_32KBP;
    CONNECT RESET;
  service:
    name: db2-lb
    type: LoadBalancer
    port: 50000
